# Generated by cucumber-sinatra. (2015-01-08 00:03:22 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/halunka.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = halunka

class halunkaWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  halunkaWorld.new
end
